export type Message = {
  id: string;
  speaker: "her" | "you";
  text: string;
  date: string;
  kind: "Message" | "My impression" | "She said" | "Event";
  source?: "screenshot";
};
export type Intention = {
  status: string;
  role: string;
  secondary: string;
  objective: string;
  custom: string;
  pace: string;
  boundaries: string;
  confirmed: boolean;
  version: number;
};
export type Claim = {
  label: "Explicit" | "Context-supported" | "Plausible" | "Unknown";
  text: string;
  sourceIds: string[];
};
export type Move = {
  id: string;
  title: string;
  description: string;
  draft: string;
  fit: string;
  tradeoff: string;
  assumption: string;
  timing: string;
  stop: string;
  branches: string[];
  sourceIds: string[];
};
export type Review = {
  id: string;
  mode: "standard" | "perspectives";
  origin: "example" | "live";
  revision: number;
  goalVersion: number;
  summary: string;
  claims: Claim[];
  unknown: string;
  question: string;
  disagreement: string;
  perspectives: { name: string; reading: string }[];
  moves: Move[];
  created: string;
  status?: string;
  selectedMessageId?: string;
};
export type Decision = {
  id: string;
  date: string;
  goal: Intention;
  stage: string;
  sourceIds: string[];
  reading: string;
  move: Move;
  expectation: string;
  actualAction: string;
  actualText: string;
  outcome: string;
  outcomeKind: string;
  revision: string;
  needsReview?: boolean;
  preparedDraft?: string;
  outcomeMessageId?: string;
  outcomeDate?: string;
  checkedInAt?: string;
};
export type Profile = {
  id: string;
  name: string;
  age: string;
  met: string;
  stage: string;
  current: string;
  stated: string;
  context: string;
  boundary: string;
  adult: boolean;
  archived: boolean;
  color: string;
  intention: Intention;
  messages: Message[];
  decisions: Decision[];
  review: Review | null;
  revision: number;
  example?: string;
};
export type Workspace = {
  profiles: Profile[];
  style: string;
  retention: "until-deleted" | "30-days" | "90-days";
  updated?: string;
};
